### ISSUE TITLE
For "Theme" setting option in description add target="_blank" for link "Customization"

### ISSUE THREAD

**Issue by furashcka** [matdave/modx-monaco#5]
It's not a problem, but when I click to "Customization" I don't want leave setting page and lost current search state of settings

![image](https://github.com/user-attachments/assets/c7445812-10fe-417f-a2bf-87380980444e)

**Comment by matdave** [comment]
I, personally, feel this is an outdated mindset. If you want a link to open in a new window, it is up to you to make that decision. You can right-click to open in a new window, or control+click.
